export const GET_PHOTOS_REQUESTED = 'GET_PHOTOS_REQUESTED';
export const GET_PHOTOS_SUCCESS = 'GET_PHOTOS_SUCCESS';
export const GET_PHOTOS_FAILED = 'GET_PHOTOS_FAILED';

export const ADD_PHOTOS_REQUESTED = 'ADD_PHOTOS_REQUESTED';
export const ADD_PHOTOS_SUCCESS = 'ADD_PHOTOS_SUCCESS';
export const ADD_PHOTOS_FAILED = 'ADD_PHOTOS_FAILED';